title: Generative AI for Networking
description: |
  <p align="center">Computer Networks and Communication Lab @ NTU<br>
  <a href="https://personal.ntu.edu.sg/dniyato/">DLab.</a></p>
show_downloads: False
google_analytics:
theme: jekyll-theme-cayman
